function CodeDefine() { 
this.def = new Array();
this.def["ert_main.c:control_flow_M_"] = {file: "ert_main_c.html",line:23,type:"var"};
this.def["ert_main.c:control_flow_MPtr"] = {file: "ert_main_c.html",line:24,type:"var"};
this.def["ert_main.c:control_flow_B"] = {file: "ert_main_c.html",line:25,type:"var"};
this.def["ert_main.c:control_flow_DW"] = {file: "ert_main_c.html",line:26,type:"var"};
this.def["ert_main.c:control_flow_U"] = {file: "ert_main_c.html",line:27,type:"var"};
this.def["ert_main.c:control_flow_Y"] = {file: "ert_main_c.html",line:28,type:"var"};
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:29,type:"var"};
this.def["ert_main.c:OverrunFlag"] = {file: "ert_main_c.html",line:30,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:31,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:48,type:"var"};
this.def["runModel"] = {file: "ert_main_c.html",line:49,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:50,type:"fcn"};
this.def["control_flow_rtZRETURN"] = {file: "control_flow_c.html",line:50,type:"var"};
this.def["control_flow_servo_dir_Init"] = {file: "control_flow_c.html",line:99,type:"fcn"};
this.def["control_flow_servo_dir"] = {file: "control_flow_c.html",line:108,type:"fcn"};
this.def["control_flow_velo_adjust_Init"] = {file: "control_flow_c.html",line:163,type:"fcn"};
this.def["control_flow_velo_adjust"] = {file: "control_flow_c.html",line:177,type:"fcn"};
this.def["control_flow_step"] = {file: "control_flow_c.html",line:231,type:"fcn"};
this.def["control_flow_initialize"] = {file: "control_flow_c.html",line:366,type:"fcn"};
this.def["control_flow_terminate"] = {file: "control_flow_c.html",line:419,type:"fcn"};
this.def["RT_MODEL_control_flow_T"] = {file: "control_flow_h.html",line:69,type:"type"};
this.def["FROM_LATTE"] = {file: "control_flow_h.html",line:77,type:"type"};
this.def["MOTOR_CONTROL"] = {file: "control_flow_h.html",line:88,type:"type"};
this.def["FROM_LATTE_FLAG"] = {file: "control_flow_h.html",line:99,type:"type"};
this.def["RETURN"] = {file: "control_flow_h.html",line:113,type:"type"};
this.def["B_servo_dir_control_flow_T"] = {file: "control_flow_h.html",line:120,type:"type"};
this.def["DW_servo_dir_control_flow_T"] = {file: "control_flow_h.html",line:126,type:"type"};
this.def["B_velo_adjust_control_flow_T"] = {file: "control_flow_h.html",line:131,type:"type"};
this.def["DW_velo_adjust_control_flow_T"] = {file: "control_flow_h.html",line:139,type:"type"};
this.def["B_control_flow_T"] = {file: "control_flow_h.html",line:149,type:"type"};
this.def["DW_control_flow_T"] = {file: "control_flow_h.html",line:161,type:"type"};
this.def["ExtU_control_flow_T"] = {file: "control_flow_h.html",line:168,type:"type"};
this.def["ExtY_control_flow_T"] = {file: "control_flow_h.html",line:173,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:90,type:"type"};
this.def["schdl_counter"] = {file: "SysTickScheduler_c.html",line:8,type:"var"};
this.def["schdl_counter_max"] = {file: "SysTickScheduler_c.html",line:9,type:"var"};
this.def["SysTickScheduler.c:SysTick_Isr"] = {file: "SysTickScheduler_c.html",line:11,type:"fcn"};
this.def["ARMCM_SysTick_Config"] = {file: "SysTickScheduler_c.html",line:39,type:"fcn"};
this.def["bootloaderBackgroundTask"] = {file: "blapp_support_c.html",line:10,type:"fcn"};
this.def["bootloaderInit"] = {file: "blapp_support_c.html",line:13,type:"fcn"};
this.def["APPDATAPOINTER"] = {file: "blapp_support_c.html",line:21,type:"var"};
this.def["APPDATACOMPLETED"] = {file: "blapp_support_c.html",line:22,type:"var"};
this.def["COMMownerROMmsg"] = {file: "blapp_support_c.html",line:29,type:"var"};
this.def["COMMownerROMmsg"] = {file: "blapp_support_c.html",line:31,type:"var"};
this.def["OkforMemServ"] = {file: "blapp_support_c.html",line:34,type:"var"};
this.def["USART2_IRQHandler"] = {file: "blapp_support_c.html",line:41,type:"fcn"};
this.def["bootloaderInit"] = {file: "blapp_support_c.html",line:47,type:"fcn"};
this.def["Error_Handler"] = {file: "blapp_support_c.html",line:77,type:"fcn"};
this.def["bootloaderBackgroundTask"] = {file: "blapp_support_c.html",line:83,type:"fcn"};
this.def["arm_cortex_m_call_thread_with_context_switch"] = {file: "m3m4m4f_multitasking_c.html",line:19,type:"fcn"};
this.def["SVC_Handler"] = {file: "m3m4m4f_multitasking_c.html",line:44,type:"fcn"};
this.def["pulStack"] = {file: "startup_stm32f4xx_c.html",line:18,type:"var"};
this.def["__main"] = {file: "startup_stm32f4xx_c.html",line:19,type:"fcn"};
this.def["Default_ResetHandler"] = {file: "startup_stm32f4xx_c.html",line:137,type:"fcn"};
this.def["startup_stm32f4xx.c:Default_Handler"] = {file: "startup_stm32f4xx_c.html",line:177,type:"fcn"};
this.def["stm32f4xx_init_board"] = {file: "stm32f4xx_init_board_c.html",line:7,type:"fcn"};
this.def["_close"] = {file: "syscalls_stm32f4xx_c.html",line:13,type:"fcn"};
this.def["_fstat"] = {file: "syscalls_stm32f4xx_c.html",line:18,type:"fcn"};
this.def["_isatty"] = {file: "syscalls_stm32f4xx_c.html",line:24,type:"fcn"};
this.def["_lseek"] = {file: "syscalls_stm32f4xx_c.html",line:29,type:"fcn"};
this.def["_open"] = {file: "syscalls_stm32f4xx_c.html",line:34,type:"fcn"};
this.def["_read"] = {file: "syscalls_stm32f4xx_c.html",line:39,type:"fcn"};
this.def["_exit"] = {file: "syscalls_stm32f4xx_c.html",line:44,type:"fcn"};
this.def["heap_end"] = {file: "syscalls_stm32f4xx_c.html",line:52,type:"var"};
this.def["_sbrk"] = {file: "syscalls_stm32f4xx_c.html",line:53,type:"fcn"};
this.def["_write"] = {file: "syscalls_stm32f4xx_c.html",line:74,type:"fcn"};
this.def["_unlink"] = {file: "syscalls_stm32f4xx_c.html",line:79,type:"fcn"};
this.def["SystemCoreClock"] = {file: "system_stm32f4xx_c.html",line:84,type:"var"};
this.def["AHBPrescTable"] = {file: "system_stm32f4xx_c.html",line:86,type:"var"};
this.def["SystemInit"] = {file: "system_stm32f4xx_c.html",line:93,type:"fcn"};
this.def["SystemCoreClockUpdate"] = {file: "system_stm32f4xx_c.html",line:135,type:"fcn"};
this.def["system_stm32f4xx.c:SetSysClock"] = {file: "system_stm32f4xx_c.html",line:184,type:"fcn"};
this.def["SystemInit_ExtMemCtl"] = {file: "system_stm32f4xx_c.html",line:271,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["control_flow_c.html"] = "../control_flow.c";
	this.html2Root["control_flow_c.html"] = "control_flow_c.html";
	this.html2SrcPath["control_flow_h.html"] = "../control_flow.h";
	this.html2Root["control_flow_h.html"] = "control_flow_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["SysTickScheduler_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/armcortexmbase/scheduler/src/SysTickScheduler.c";
	this.html2Root["SysTickScheduler_c.html"] = "SysTickScheduler_c.html";
	this.html2SrcPath["blapp_support_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/stm32f4discovery/src/blapp_support.c";
	this.html2Root["blapp_support_c.html"] = "blapp_support_c.html";
	this.html2SrcPath["m3m4m4f_multitasking_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/armcortexmbase/scheduler/src/m3m4m4f_multitasking.c";
	this.html2Root["m3m4m4f_multitasking_c.html"] = "m3m4m4f_multitasking_c.html";
	this.html2SrcPath["startup_stm32f4xx_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/stm32f4discovery/src/startup_stm32f4xx.c";
	this.html2Root["startup_stm32f4xx_c.html"] = "startup_stm32f4xx_c.html";
	this.html2SrcPath["stm32f4xx_init_board_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/stm32f4discovery/src/stm32f4xx_init_board.c";
	this.html2Root["stm32f4xx_init_board_c.html"] = "stm32f4xx_init_board_c.html";
	this.html2SrcPath["syscalls_stm32f4xx_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/stm32f4discovery/src/syscalls_stm32f4xx.c";
	this.html2Root["syscalls_stm32f4xx_c.html"] = "syscalls_stm32f4xx_c.html";
	this.html2SrcPath["system_stm32f4xx_c.html"] = "../../../../../ProgramData/MATLAB/SupportPackages/R2020a/toolbox/target/supportpackages/stm32f4discovery/src/system_stm32f4xx.c";
	this.html2Root["system_stm32f4xx_c.html"] = "system_stm32f4xx_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","control_flow_c.html","control_flow_h.html","rtwtypes_h.html","rtmodel_h.html","MW_target_hardware_resources_h.html","SysTickScheduler_c.html","blapp_support_c.html","m3m4m4f_multitasking_c.html","startup_stm32f4xx_c.html","stm32f4xx_init_board_c.html","syscalls_stm32f4xx_c.html","system_stm32f4xx_c.html"];
